name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "**.java"

jobs:
  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v5.0.2
